apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer
  namespace: k8s-monitor
  labels:
    app: grafana-renderer
spec:
  selector:
    app: grafana-renderer
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP
